### ISSUE TITLE
Question around Firebase

### ISSUE THREAD

**Issue by eferrervaughn** [justrossthings/react-redux-boiler#12]
First off this is one of the better boiler plates I have found on the web. I saw that you recommended using Firebase which is something I have spent a lot of time with.

I am having a hard time understanding how to integrate firebase with this boiler plate. So here are my questions:

1. For integrating firebase, do you recommended the Stephen Grider method? (https://www.youtube.com/watch?v=UHJq5NOtNG4)  or using React-Fire?
2. Would app state be worth storing on firebase? or using firebase purely for the hosting and authentication?
3. For fetching firebase data, would that logic be housed in store.js? actions?

Any help would be greatly appreciated!

**Comment by baebb** [comment]
@eferrervaughn Glad to hear it! Update coming soon 👾 

I think too much state gets stored with React-Fire unnecessarily and encourages a weird pattern that can be hard to manage. I've used Grider's method in the past, but there might be a better solution depending on what you need from Firebase (hosting, DB, auth). I can help- just tell me what you're trying to achieve 😃  

For interacting with Firebase I use Thunk actions- 
[Adding an item to your Firebase DB example](https://github.com/justrossthings/takethis-react/blob/d724d5ff8c4576668289571a2fc266053d254e6e/src/actions/index.js#L62)
[Authentication with Firebase example](https://github.com/justrossthings/takethis-react/blob/d724d5ff8c4576668289571a2fc266053d254e6e/src/actions/index.js#L152)

**Comment by eferrervaughn** [comment]
@justrossthings Thanks for responding. Your examples already have helped me understand a little bit better. As for where I need help with Firebase, I know I am going to use it for hosting, DB, auth & CDN.

I have a good handle on Auth and Hosting. I need a little help understanding the DB side. Here are some top of mind questions for me:

1. Where should the firebase logic be housed? In the actions? Containers?
2. Should actions be created off of Firebase onValue events? on child added events? Both?
3. When/where should I push to the database?

Also I had a separate question for you:
Using your boiler plate, its pretty clear how the state only gets updated on the route changing. What I am confused about is how to updated the state without the route changing?

Once again thanks hearing me out.

**Comment by baebb** [comment]
@eferrervaughn 

1. Firebase logic should be in actions, which dispatch changes through to the store which update the containers/components
2. You can do this but it's a bit complex. Can't say I've done it before
3. Push to the DB through an action like you would normally

Are you talking about updating the store? I would do it via dispatching an action which updates store through the reducers etc etc. Or are you talking about component state? 

// yourContainer.js
```
import {funcYouWannaUse} from './actions/index';
// other container stuff stuff
dispatch(funcYouWannaUse(params))
```

Hope this helps!

**Comment by baebb** [comment]
PS. It's a lot easier if you don't think of Firebase as something too different from a regular DB

**Comment by eferrervaughn** [comment]
Thank you for your help Ross. I got it all hooked up. Plus I making it work with Firestore now.
