### ISSUE TITLE
Sass Loader

### ISSUE THREAD

**Issue by eferrervaughn** [justrossthings/react-redux-boiler#13]
Hey Ross,

Another question for you. Is there a reason you use Sass loader instead of doing the styles inline in the JSX files?

**Comment by baebb** [comment]
@eferrervaughn Old-habits die hard I guess. I've spent many years carefully balancing sass files to make reusable styles without conflicts so it feels right keeping to that

**Comment by depadiernos** [comment]
I’ve recently started using styled-components. This allows a lot of the same features as sass like variables and nested selectors. Maybe the familiar syntax would help you get into inline styles?

**Comment by eferrervaughn** [comment]
@depadiernos Thanks thats really cool! I wonder if it works well with different component libraries

**Comment by baebb** [comment]
@depadiernos heard about styled-components plenty of times but never tried them. Thanks! I'll give it a peep and hopefully be able to integrate into this boiler if plays nicely with react bootstrap

**Comment by depadiernos** [comment]
I’ve used it with react-semantic-ui and it’s pretty seemless. Though having to wrangle css in two places made me drop semantic-ui-css and just wrapped tue react-semantic-ui components with styled-components for styling. Hopefully it works for you.

**Comment by depadiernos** [comment]
Sorry, I know this issue has been marked closed, but I just wanted to add [this](https://stackoverflow.com/questions/45895416/styled-components-and-react-bootstrap) example of react-bootstrap and styled-components working together.

**Comment by baebb** [comment]
@depadiernos great example! One question, what is the best practice for putting styled component styling ? On component's own js or a separate file?

**Comment by depadiernos** [comment]
Not sure about 'best practice', but I've been following a mostly 'Single File Component' style. I declare the styled component and use it in the same file to keep the style, markup (jsx) and the component code together.
I've seen examples where the developer has put his styled components in separate files inside a 'common' folder. But I do prefer the clarity of an SFC approach, though.
