### ISSUE TITLE
Support for testing framework

### ISSUE THREAD

**Issue by thellimist** [justrossthings/react-redux-boiler#3]
- Support for testing framework
- Write tests for current example.
- Have an example of how to write tests on Redux (or have a link to a good source)

**Comment by baebb** [comment]
There is testing framework set up in mocha & chai in /tests, but it's not mentioned cause I will likely migrate to [Enzyme](https://github.com/airbnb/enzyme) in the near future

**Comment by baebb** [comment]
merge'd: https://github.com/justrossthings/react-redux-boiler/pull/9
